defmodule Jev.Wire do
  @moduledoc """
  The `/v1/systemone` response as JSON-shaped structs.

  These are boundary codecs generated by `JSONCodec` from the struct and type
  declarations below. `Jev.HTTP` decodes a response body into a
  `Jev.Wire.Response`, and `Jev.reply/3` turns that into the plain reply map.
  Nothing else in the library sees the wire shape, and nothing in your code
  needs to.

  The three answer kinds share one struct, `Jev.Wire.Answer`, because that is
  how the API sends them: a `type` and the fields of that type. Numbers are
  `number()` rather than `float()` since a server may send `1` for a
  probability of one. Unknown keys are ignored, so servers that add fields
  keep working; a missing `answers`, a non-numeric probability, or an unknown
  `type` is a `JSONCodec.Error` with the path of the offending field.

  `Jev.Wire.Response.schema/0` is the JSON Schema of what the client accepts.
  """

  defmodule Usage do
    @moduledoc "Token counts. Both default to zero when the server omits them."
    use JSONCodec, strict: true, fast_path: :json

    defstruct input_tokens: 0, output_tokens: 0

    @type t :: %__MODULE__{input_tokens: non_neg_integer(), output_tokens: non_neg_integer()}
  end

  defmodule Answer do
    @moduledoc """
    One answer. `noul`, `choice`, or `score` is set according to `type`;
    `confidence`, `legend`, and `probabilities` accompany a choice or score.
    """
    use JSONCodec, strict: true, fast_path: :json

    defstruct [:type, :noul, :choice, :score, :confidence, :legend, probabilities: %{}]

    @type t :: %__MODULE__{
            type: :noul | :choice | :score | nil,
            noul: number() | nil,
            choice: String.t() | nil,
            score: number() | nil,
            confidence: number() | nil,
            legend: %{String.t() => String.t()} | nil,
            probabilities: %{String.t() => number()}
          }

    codec(:type, atom: {:enum, [:noul, :choice, :score]})
  end

  defmodule Response do
    @moduledoc "The response body: the model that answered, one answer per question, and usage."
    use JSONCodec, strict: true, fast_path: :json

    defstruct [:model, :answers, usage: %Jev.Wire.Usage{}]

    @type t :: %__MODULE__{
            model: String.t() | nil,
            answers: %{String.t() => Jev.Wire.Answer.t()},
            usage: Jev.Wire.Usage.t() | nil
          }
  end
end
